name = "Clean Blog"
license = "MIT"
description = "A clean, minimal blog theme with pinned posts"
tags = ["blog", "minimal", "clean", "responsive"]
features = ["pinned posts", "responsive", "clean design"]
min_version = "0.41.0"

[author]
  name = "Your Name"
  homepage = "https://yoursite.com"
